# Generated by Django 6.0.5 on 2026-05-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetaSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='სახელი')),
                ('business_name', models.CharField(max_length=200, verbose_name='ბიზნესის სახელი')),
                ('contact', models.CharField(max_length=200, verbose_name='ტელეფონი ან Email')),
                ('business_type', models.CharField(max_length=200, verbose_name='ბიზნესის ტიპი')),
                ('message', models.TextField(blank=True, verbose_name='შეტყობინება')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Beta რეგისტრაცია',
                'verbose_name_plural': 'Beta რეგისტრაციები',
                'ordering': ['-created_at'],
            },
        ),
    ]
